packages:
    -   apps/*
    -   packages/*
    -   tools/*

ignoredBuiltDependencies:
    -   '@tailwindcss/oxide'

onlyBuiltDependencies:
    -   '@sveltejs/kit'
    -   esbuild
    -   unrs-resolver
